num1 = input("Enter 1st Number")
num2 = input("Enter 2nd number")
print(("Sum of numbers = "), int(num1) + int(num2))
print(("Subtraction of numbers = "),int(num1) - int(num2))
print(("Multiplication of numbers = "), int(num1) * int(num2))
print(("Division of numbers = "), int(num1) / int(num2))